Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"
  config.vm.box_check_update = false
  #config.vm.network :public_network,
  #  :dev => "virbr0",
  #  :mode => "bridge",
  #  :type => "bridge"
  
  config.vm.provision "file", source: "../../ubuntu/kind/create-cluster.yaml", destination: "/home/vagrant/create-cluster.yaml"
  config.vm.provision "file", source: "../../ubuntu/haproxy/haproxy-ingress-values.yaml", destination: "/home/vagrant/haproxy-ingress-values.yaml"
  config.vm.provision "file", source: "../../ubuntu/metallb/lb-pool-cm.yaml", destination: "/home/vagrant/lb-pool-cm.yaml"
  config.vm.provision "file", source: "../../ubuntu/applications/nginx", destination: "/home/vagrant/applications/nginx"

  config.vm.define "kindmaster" do |node|

    node.vm.provider :libvirt do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end

    node.vm.hostname = "kindmaster"

    node.vm.provision "setup-container-runtime", type: "shell", :path => "../../ubuntu/docker/install-docker.sh"
    node.vm.provision "setup-container-orchestration", type: "shell", :path => "../../ubuntu/kind/install-kind.sh"
    node.vm.provision "setup-kubectl", type: "shell", :path => "../../ubuntu/kubectl/install-kubectl.sh"
    node.vm.provision "setup-helm", type: "shell", :path => "../../ubuntu/helm/install-helm.sh"

    node.vm.provision "create-kind-cluster", type: "shell", :path => "../../ubuntu/kind/create-cluster.sh"
    node.vm.provision "setup-metallb", type: "shell", :path => "../../ubuntu/metallb/install-metallb.sh"
    node.vm.provision "setup-haproxy", type: "shell", :path => "../../ubuntu/haproxy/install-haproxy.sh"
    node.vm.provision "setup-iptables", type: "shell", :path => "../../ubuntu/ingress/iptables_libvirt.sh"

  end

end  