apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-varvas-net
  namespace: web
spec:
  secretName: k3s-varvas-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: varvas.net
  dnsNames:
  - varvas.net